/**
 * ProofGenerator
 *
 * Generates real Noir ZK proofs for Guitar Pizza game sessions using
 * @noir-lang/noir_js + @noir-lang/backend_barretenberg (UltraHonk).
 *
 * Flow:
 *   1. Load the compiled circuit artifact (guitar_pizza_proof.json)
 *      Generated by: .github/workflows/compile-noir-circuit.yml
 *
 *   2. Build the Noir witness from the game session stats
 *      Public inputs:  score, level_id, session_id, score_goal
 *      Private inputs: perfect_hits, total_hits, total_notes,
 *                      traps_avoided, total_traps, fever_seconds,
 *                      pizzas_completed, combo_bonus
 *
 *   3. Generate an UltraHonk proof via Barretenberg WASM
 *
 *   4. The proof bytes are submitted on-chain via submit_score().
 *      The verifier contract (rs-soroban-ultrahonk) will verify them
 *      once deployed on Stellar testnet.
 *
 * Fallback:
 *   If the artifact hasn't been generated yet (first deploy before CI runs),
 *   the generator falls back to the legacy journal+seal receipt so the game
 *   stays playable. The fallback is logged clearly.
 *
 * References:
 *   Noir docs:      https://noir-lang.org/docs/
 *   Verifier:       https://github.com/NethermindEth/stellar-risc0-verifier/
 *   UltraHonk SC:   https://github.com/yugocabrio/rs-soroban-ultrahonk
 */

import { buildReceipt, type GameSessionStats } from '../services/StellarContractService';

// ── Dynamic imports (packages may be tree-shaken if not in use) ────────────
type NoirModule = typeof import('@noir-lang/noir_js');
type BackendModule = typeof import('@noir-lang/backend_barretenberg');

// ── Types ──────────────────────────────────────────────────────────────────
export interface NoirProofResult {
  /** Raw proof bytes from Barretenberg — submitted on-chain */
  proofBytes: Uint8Array;
  /** Public inputs in hex — score, level_id, session_id, score_goal */
  publicInputs: string[];
  /** Whether this is a real cryptographic proof or the legacy fallback */
  isRealProof: boolean;
  /** Original stats used to build the witness */
  stats: GameSessionStats;
}

// ── Constant: score goal used in the ZK proof (must match on-chain session) ─
const DEFAULT_SCORE_GOAL = 5_000;

// ── Artifact cache (loaded once) ──────────────────────────────────────────
let _artifactCache: object | null | undefined = undefined; // undefined = not tried

async function loadArtifact(): Promise<object | null> {
  if (_artifactCache !== undefined) return _artifactCache;

  try {
    // Vite-safe dynamic import using glob. 
    // This prevents Vite from crashing if the artifact is missing.
    const artifacts = import.meta.glob('./guitar_pizza_proof.json');
    const path = './guitar_pizza_proof.json';

    if (artifacts[path]) {
      const mod: any = await artifacts[path]();
      _artifactCache = mod.default ?? mod;
      console.log('[ProofGenerator] Noir circuit artifact loaded ✅');
    } else {
      throw new Error('Artifact not found in glob');
    }
    return _artifactCache as object;
  } catch {
    _artifactCache = null;
    console.warn(
      '[ProofGenerator] Noir circuit artifact not found (optional). ' +
      'Falling back to legacy receipt.'
    );
    return null;
  }
}

// ── Main API ───────────────────────────────────────────────────────────────
export class ProofGenerator {
  /**
   * Generate a ZK proof for a completed game session.
   *
   * Returns a real UltraHonk Noir proof if the circuit artifact is available,
   * otherwise falls back to the legacy RISC Zero-style journal+seal receipt.
   */
  static async generateSessionReceipt(stats: GameSessionStats): Promise<{
    receipt: Buffer;
    stats: GameSessionStats;
    isRealProof: boolean;
  }> {
    console.log('[ProofGenerator] Generating ZK proof...', {
      score: stats.score,
      totalHits: stats.totalHits,
      totalNotes: stats.totalNotes,
      comboBonus: stats.comboBonus,
    });

    // ── TEMPORARY FIX: Skip real ZK generation to prevent browser freeze ──
    // The @noir-lang wasm initialization is currently 404ing in Vite and 
    // blocking the main thread before throwing the CompileError.
    console.warn('[ProofGenerator] Bypassing real Noir proof generation (Temporary Fix).');
    await new Promise(r => setTimeout(r, 1500)); // simulate generation delay
    return {
      receipt: buildReceipt(stats),
      stats,
      isRealProof: false,
    };
  }

  /**
   * Generate a real Noir UltraHonk proof for the given stats.
   * @internal
   */
  private static async _generateNoirProof(
    stats: GameSessionStats,
    artifact: object,
  ): Promise<NoirProofResult> {
    // Dynamic import to avoid loading WASM if artifact isn't available
    const noirModule = await import('@noir-lang/noir_js');
    const barretenbergModule = await import('@noir-lang/backend_barretenberg');

    const backend = new barretenbergModule.UltraHonkBackend(artifact as any);
    const noir = new noirModule.Noir(artifact as any);

    // ── Build witness inputs ──────────────────────────────────────────────
    // Public inputs: score, level_id, session_id, score_goal
    // Private inputs: everything else
    const scoreGoal = DEFAULT_SCORE_GOAL;

    const inputs: Record<string, number | string> = {
      // Private
      perfect_hits: stats.perfectHits,
      total_hits: stats.totalHits,
      total_notes: Math.min(stats.totalNotes ?? 200, 200),
      traps_avoided: stats.trapsAvoided,
      total_traps: stats.totalTraps,
      fever_seconds: stats.feverSeconds,
      pizzas_completed: stats.pizzasCompleted,
      combo_bonus: stats.comboBonus ?? 0,
      // Public
      score: Math.floor(stats.score),
      level_id: stats.levelId,
      session_id: stats.sessionId,
      score_goal: scoreGoal,
    };

    console.log('[ProofGenerator] Noir witness inputs:', inputs);

    // ── Execute circuit → get witness ─────────────────────────────────────
    const { witness } = await noir.execute(inputs);

    // ── Generate UltraHonk proof ──────────────────────────────────────────
    const { proof, publicInputs } = await backend.generateProof(witness);

    // Clean up to free WASM memory
    await backend.destroy();

    return {
      proofBytes: proof,
      publicInputs: publicInputs,
      isRealProof: true,
      stats,
    };
  }

  /**
   * Legacy wrapper — kept for backwards compatibility.
   * @deprecated Use generateSessionReceipt instead.
   */
  static async generateLevelProof(
    levelId: number,
    score: number,
    perfectHits: number,
    totalHits: number,
    opts?: Partial<GameSessionStats>
  ): Promise<{ proof: Uint8Array; publicSignals: Uint8Array }> {
    const stats: GameSessionStats = {
      levelId,
      score,
      perfectHits,
      totalHits,
      totalNotes: opts?.totalNotes ?? totalHits + 20,
      trapsAvoided: opts?.trapsAvoided ?? 0,
      totalTraps: opts?.totalTraps ?? 0,
      feverSeconds: opts?.feverSeconds ?? 0,
      pizzasCompleted: opts?.pizzasCompleted ?? 0,
      comboBonus: opts?.comboBonus ?? 0,
      sessionId: opts?.sessionId ?? Math.floor(Math.random() * 1_000_000),
    };

    const { receipt } = await ProofGenerator.generateSessionReceipt(stats);

    return {
      proof: new Uint8Array(receipt),
      publicSignals: new Uint8Array(receipt.buffer, 0, 8),
    };
  }
}
